name: Release the SDK

on:
  pull_request:
    branches:
      - stable

jobs:
  build-and-release:
    name: Check and release

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Publish to Maven
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publish
            -Psigning.gnupg.passphrase='${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}'
            -Psigning.gnupg.keyName='${{secrets.OSSRH_GPG_SECRET_KEY_ID}}'
            -PsonatypeUsername='${{secrets.OSSRH_USERNAME}}'
            -PsonatypePassword='${{secrets.OSSRH_PASSWORD}}'

        env:
          GITHUB_TOKEN: ${{ secrets.FULL_TOKEN }}

