name: Release the SDK

on:
  release:
    types: [ published ]

jobs:
  build-and-release:
    name: Check and release

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publish
            -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
            -Psigning.gnupg.keyName=${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}
            -PsonatypeUsername=${{ secrets.OSSRH_USERNAME }}
            -PsonatypePassword=${{ secrets.OSSRH_TOKEN }}
